version: "3.8"

services:
  humanvision_app:
    build:
      context: ./core
      dockerfile: Dockerfile
      args:
        WWWUSER: "${UID:-1000}"
        WWWGROUP: "${GID:-1000}"
    container_name: humanvision_laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./core:/var/www
    depends_on:
      - humanvision_mysqldb
      - humanvision_mongodb
    networks:
      - humanvision_network

  humanvision_angular:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: humanvision_angular_app
    restart: unless-stopped
    working_dir: /usr/src/app
    ports:
      - "4200:4200"
    volumes:
      - ./app:/usr/src/app
    command: npm start
    networks:
      - humanvision_network

  humanvision_nginx:
    image: nginx:alpine
    container_name: humanvision_nginx
    restart: unless-stopped
    ports:
      - "9400:2002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./core:/var/www
    depends_on:
      - humanvision_app
      - humanvision_angular
    networks:
      - humanvision_network

  humanvision_mysqldb:
    image: mysql:8
    container_name: humanvision_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: humanvision
      MYSQL_USER: core
      MYSQL_PASSWORD: core
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - humanvision_mysqldb_data:/var/lib/mysql
    networks:
      - humanvision_network

  humanvision_mongodb:
    image: mongo:latest
    container_name: humanvision_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - humanvision_mongodb_data:/data/db
    networks:
      - humanvision_network

  humanvision_ai_api:
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    container_name: humanvision_ai_api
    ports:
      - "3423:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    networks:
      - humanvision_network

  humanvision_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: humanvision_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: humanvision_mysqldb
      PMA_PORT: 3306
    ports:
      - "9800:80"
    depends_on:
      - humanvision_mysqldb
    networks:
      - humanvision_network

volumes:
  humanvision_mysqldb_data:
  humanvision_mongodb_data:

networks:
  humanvision_network:
    driver: bridge
